version: '3.8'
services:
   usb-app:
     build: .
     image: name:1.0
     env_file:
       - .env
     ports:
       - 8000:8000
     volumes:
       - ./certs/localhost.crt:/app/localhost.crt
       - ./certs/device.key:/app/device.key
       - ./:/app
       - /etc/localtime:/etc/localtime:ro
     command: uvicorn main:app --host 0.0.0.0 --port 8000

   nginx:
     image: nginx:latest
     ports:
       - "80:80"
       - "443:443"
     volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./certs/localhost.crt:/etc/nginx/localhost.crt
         - ./certs/device.key:/etc/nginx/device.key
         - /etc/localtime:/etc/localtime:ro
     depends_on:
       - usb-app